blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://modernwarfarecubed.featurebase.app/
    about: |
      We use Featurebase for feature requests.
      Don't worry; you can easily connect to it via GitHub, Discord or Google.
  - name: Red Studio Discord Help
    url: https://discord.gg/hKpUYx7VwS
    about: Get help on the Red Studio Discord.
